apiVersion: v1
kind: Service
metadata:
  name: recommendation-storage
  namespace: gctoolsv2
  labels:
    name: recommendation-storage
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: recommendation-storage

