apiVersion: v1
kind: Service
metadata:
  name: graphql-server-http
  namespace: gctoolsv2
  labels:
    name: graphql-server-http
  annotations:
    VIRTUAL_HOST: "gcrec.lpss.me"
    VIRTUAL_PORT: "3001"
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    name: graphql-server
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-server-ws
  namespace: gctoolsv2
  labels:
    name: graphql-server-ws
  annotations:
    VIRTUAL_HOST: "gcrec-db.lpss.me"
    VIRTUAL_PORT: "3002"
spec:
  ports:
  - port: 3002
    targetPort: 3002
  selector:
    name: graphql-server

